name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy spring boot
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven # to avoid installing it again everytime we modify the pipeline

      - name: Build with Maven
        run: mvn clean package

      - name: List files
        run: ls ./target

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls ~/.ssh
          ssh-keyscan -H ${{ secrets.AWS_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy Jar file to AWS server
        run: |
          ssh -i ~/.ssh/id_rsa \
            ${{ secrets.AWS_SERVER_USER }}@${{ secrets.AWS_SERVER_IP }} "mkdir ~/footballersmarketspringbackend/test"
          scp -i "~/.ssh/id_rsa" ./target/demo-cicd-app.jar \
            ${{ secrets.AWS_SERVER_USER }}@${{ secrets.AWS_SERVER_IP }}:~/footballersmarketspringbackend/test/demo-cicd-app.jar
          ssh -i ~/.ssh/id_rsa \
            ${{ secrets.AWS_SERVER_USER }}@${{ secrets.AWS_SERVER_IP }} "ls -lh ~/footballersmarketspringbackend/test"
#      - name: Run test script on AWS server
#        run: |
#          ssh -i ~/.ssh/id_rsa \
#            ${{ secrets.AWS_SERVER_USER }}@${{ secrets.AWS_SERVER_IP }} << 'EOF'
#
#            echo "SSH connection successful!"
#            ls
#            docker ps
#          EOF
#      - name: Cleanup SSH key
#        if: always()
#        run: rm -f ~/.ssh/id_rsa